# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screens/ui/admin_ui/admin_inventory/barcode.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(459, 336)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.barcodeLBL = QtWidgets.QLabel(Dialog)
        self.barcodeLBL.setAlignment(QtCore.Qt.AlignCenter)
        self.barcodeLBL.setObjectName("barcodeLBL")
        self.verticalLayout.addWidget(self.barcodeLBL)
        self.dialogBox = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialogBox.sizePolicy().hasHeightForWidth())
        self.dialogBox.setSizePolicy(sizePolicy)
        self.dialogBox.setObjectName("dialogBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dialogBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.printBTN = QtWidgets.QPushButton(self.dialogBox)
        self.printBTN.setStyleSheet("QPushButton {\n"
"    background-color: #67B99A;\n"
"    color: white;\n"
"    border: 2px solid #67B99A;\n"
"    padding: 8px 16px;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5CAE8B;\n"
"    border: 2px solid #5CAE8B;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #4D9C7F;\n"
"    border: 2px solid #4D9C7F;\n"
"}")
        self.printBTN.setObjectName("printBTN")
        self.horizontalLayout.addWidget(self.printBTN)
        self.cancelBTN = QtWidgets.QPushButton(self.dialogBox)
        self.cancelBTN.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid #67B99A;\n"
"    color: black;\n"
"    padding: 8px 16px;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #4D926D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;\n"
"    border: 2px solid #265C42;\n"
"}")
        self.cancelBTN.setObjectName("cancelBTN")
        self.horizontalLayout.addWidget(self.cancelBTN)
        self.verticalLayout.addWidget(self.dialogBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.barcodeLBL.setText(_translate("Dialog", "bar"))
        self.printBTN.setText(_translate("Dialog", "Print File"))
        self.cancelBTN.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
