# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'posPayment.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1711, 761)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.navbar_2 = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navbar_2.sizePolicy().hasHeightForWidth())
        self.navbar_2.setSizePolicy(sizePolicy)
        self.navbar_2.setStyleSheet("QWidget {\n"
"    border-right: 3px solid #D8DBD9;\n"
"}\n"
"")
        self.navbar_2.setObjectName("navbar_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.navbar_2)
        self.verticalLayout_6.setSpacing(7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.homeBTN_2 = QtWidgets.QPushButton(self.navbar_2)
        self.homeBTN_2.setMinimumSize(QtCore.QSize(100, 100))
        self.homeBTN_2.setMaximumSize(QtCore.QSize(100, 100))
        self.homeBTN_2.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid #67B99A;\n"
"    color: black;\n"
"    padding: 8px 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #4D926D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;\n"
"    border: 2px solid #265C42;\n"
"}")
        self.homeBTN_2.setObjectName("homeBTN_2")
        self.verticalLayout_6.addWidget(self.homeBTN_2)
        self.menuBTN_2 = QtWidgets.QPushButton(self.navbar_2)
        self.menuBTN_2.setMinimumSize(QtCore.QSize(100, 100))
        self.menuBTN_2.setMaximumSize(QtCore.QSize(100, 100))
        self.menuBTN_2.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid #67B99A;\n"
"    color: black;\n"
"    padding: 8px 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #4D926D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;\n"
"    border: 2px solid #265C42;\n"
"}")
        self.menuBTN_2.setObjectName("menuBTN_2")
        self.verticalLayout_6.addWidget(self.menuBTN_2)
        self.paymentBTN_2 = QtWidgets.QPushButton(self.navbar_2)
        self.paymentBTN_2.setMinimumSize(QtCore.QSize(100, 100))
        self.paymentBTN_2.setMaximumSize(QtCore.QSize(100, 100))
        self.paymentBTN_2.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid #67B99A;\n"
"    color: black;\n"
"    padding: 8px 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #4D926D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;\n"
"    border: 2px solid #265C42;\n"
"}")
        self.paymentBTN_2.setObjectName("paymentBTN_2")
        self.verticalLayout_6.addWidget(self.paymentBTN_2)
        self.orderBTN_2 = QtWidgets.QPushButton(self.navbar_2)
        self.orderBTN_2.setMinimumSize(QtCore.QSize(100, 100))
        self.orderBTN_2.setMaximumSize(QtCore.QSize(100, 100))
        self.orderBTN_2.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid #67B99A;\n"
"    color: black;\n"
"    padding: 8px 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #4D926D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;\n"
"    border: 2px solid #265C42;\n"
"}")
        self.orderBTN_2.setObjectName("orderBTN_2")
        self.verticalLayout_6.addWidget(self.orderBTN_2)
        self.backBTN_2 = QtWidgets.QPushButton(self.navbar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBTN_2.sizePolicy().hasHeightForWidth())
        self.backBTN_2.setSizePolicy(sizePolicy)
        self.backBTN_2.setMinimumSize(QtCore.QSize(100, 100))
        self.backBTN_2.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.backBTN_2.setFont(font)
        self.backBTN_2.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid #67B99A;\n"
"    color: black;\n"
"    padding: 8px 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #4D926D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;\n"
"    border: 2px solid #265C42;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logos/Icons/entypo_back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backBTN_2.setIcon(icon)
        self.backBTN_2.setAutoRepeat(False)
        self.backBTN_2.setObjectName("backBTN_2")
        self.verticalLayout_6.addWidget(self.backBTN_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.navbar_2, 1, 0, 1, 1)
        self.header_2 = QtWidgets.QWidget(self.frame)
        self.header_2.setStyleSheet("QWidget {\n"
"    border-bottom: 3px solid #D8DBD9; \n"
"}\n"
"")
        self.header_2.setObjectName("header_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.header_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.header_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setStyleSheet("QLabel {\n"
"    color: #67B99A;\n"
"    font-size: 45px;\n"
"}")
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.frame_3 = QtWidgets.QFrame(self.header_2)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    color: black;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"    color: black;\n"
"}")
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.gridLayout_2.addWidget(self.header_2, 0, 0, 1, 2)
        self.contentContainer_2 = QtWidgets.QFrame(self.frame)
        self.contentContainer_2.setObjectName("contentContainer_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.contentContainer_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.mainContent_2 = QtWidgets.QWidget(self.contentContainer_2)
        self.mainContent_2.setObjectName("mainContent_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.mainContent_2)
        self.horizontalLayout_6.setContentsMargins(25, 25, 50, 25)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.leftContent_2 = QtWidgets.QWidget(self.mainContent_2)
        self.leftContent_2.setMinimumSize(QtCore.QSize(1000, 0))
        self.leftContent_2.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.leftContent_2.setObjectName("leftContent_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.leftContent_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.leftContent_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.label_15 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel {\n"
"    color: #67B99A;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel {\n"
"    color: #67B99A;\n"
"}")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.verticalLayout_9.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.leftContent_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_11.setContentsMargins(100, 25, 100, 25)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.listView = QtWidgets.QListView(self.widget_3)
        self.listView.setObjectName("listView")
        self.verticalLayout_11.addWidget(self.listView)
        spacerItem4 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem4)
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 75))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #F1A40E;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E1920C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #C77908;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_11.addWidget(self.pushButton)
        self.verticalLayout_9.addWidget(self.widget_3)
        self.horizontalLayout_6.addWidget(self.leftContent_2)
        spacerItem5 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.rightContent_2 = QtWidgets.QWidget(self.mainContent_2)
        self.rightContent_2.setObjectName("rightContent_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.rightContent_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_4 = QtWidgets.QWidget(self.rightContent_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_19 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_8.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_8.addWidget(self.label_20)
        self.label_25 = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("QLabel {\n"
"    color: #67B99A;\n"
"}")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_8.addWidget(self.label_25)
        self.verticalLayout_10.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.rightContent_2)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setContentsMargins(0, 10, 0, 10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_5.setMinimumSize(QtCore.QSize(150, 75))
        self.pushButton_5.setMaximumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #07BEB8;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #06AFA8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #059A96;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 1, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_3.setMinimumSize(QtCore.QSize(150, 75))
        self.pushButton_3.setMaximumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #07BEB8;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #06AFA8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #059A96;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_4.setMinimumSize(QtCore.QSize(150, 75))
        self.pushButton_4.setMaximumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #07BEB8;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #06AFA8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #059A96;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 1, 2, 1, 1)
        self.verticalLayout_10.addWidget(self.widget_5)
        self.widget_8 = QtWidgets.QWidget(self.rightContent_2)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_22 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_13.addWidget(self.label_22)
        self.widget_7 = QtWidgets.QWidget(self.widget_8)
        self.widget_7.setStyleSheet("QWidget {\n"
"    background-color: #C4FFF9;\n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_10.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_21 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_10.addWidget(self.label_21)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background: transparent;\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"    border-bottom: 1px solid black;\n"
"}\n"
"")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_10.addWidget(self.lineEdit)
        self.verticalLayout_13.addWidget(self.widget_7)
        self.verticalLayout_10.addWidget(self.widget_8)
        self.widget_10 = QtWidgets.QWidget(self.rightContent_2)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_24 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_14.addWidget(self.label_24)
        self.widget_9 = QtWidgets.QWidget(self.widget_10)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_11.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_23 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_11.addWidget(self.label_23)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background: transparent;\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"    border-bottom: 1px solid black;\n"
"}\n"
"")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_11.addWidget(self.lineEdit_2)
        self.verticalLayout_14.addWidget(self.widget_9)
        self.verticalLayout_10.addWidget(self.widget_10)
        self.orderList_2 = QtWidgets.QListWidget(self.rightContent_2)
        self.orderList_2.setObjectName("orderList_2")
        self.verticalLayout_10.addWidget(self.orderList_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.rightContent_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 75))
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #99E2B4;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7FD69E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #66B97E;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_10.addWidget(self.pushButton_2)
        self.horizontalLayout_6.addWidget(self.rightContent_2)
        self.verticalLayout_8.addWidget(self.mainContent_2)
        self.gridLayout_2.addWidget(self.contentContainer_2, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeBTN_2.setText(_translate("MainWindow", "Home"))
        self.menuBTN_2.setText(_translate("MainWindow", "Menu"))
        self.paymentBTN_2.setText(_translate("MainWindow", "Payment"))
        self.orderBTN_2.setText(_translate("MainWindow", "Order"))
        self.backBTN_2.setText(_translate("MainWindow", "Back"))
        self.label_10.setText(_translate("MainWindow", "POS"))
        self.label_11.setText(_translate("MainWindow", "November 28th 2023, 12:07AM"))
        self.label_12.setText(_translate("MainWindow", "Juan Dela Cruz"))
        self.label_13.setText(_translate("MainWindow", "ORDER #:"))
        self.label_14.setText(_translate("MainWindow", "1239435"))
        self.label_15.setText(_translate("MainWindow", "TABLE:"))
        self.label_16.setText(_translate("MainWindow", "2"))
        self.label_17.setText(_translate("MainWindow", "TIME:"))
        self.label_18.setText(_translate("MainWindow", "12:07 AM"))
        self.pushButton.setText(_translate("MainWindow", "CANCEL ORDER"))
        self.label_19.setText(_translate("MainWindow", "RECEIPT"))
        self.label_20.setText(_translate("MainWindow", "GUEST:"))
        self.label_25.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "SENIOR/PWD"))
        self.label_26.setText(_translate("MainWindow", "PAYMENT METHOD"))
        self.pushButton_3.setText(_translate("MainWindow", "CASH"))
        self.pushButton_4.setText(_translate("MainWindow", "GCASH"))
        self.label_27.setText(_translate("MainWindow", "APPLY DISCOUNT"))
        self.label_22.setText(_translate("MainWindow", "PAID IN CASH"))
        self.label_21.setText(_translate("MainWindow", "ADD CASH"))
        self.label_24.setText(_translate("MainWindow", "PAID IN E-WALLET"))
        self.label_23.setText(_translate("MainWindow", "ENTER REFERENCE #"))
        self.pushButton_2.setText(_translate("MainWindow", "PAY NOW"))
import resourceFile_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
