# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screens/ui/password/passwordRecovery.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.header = QtWidgets.QWidget(self.frame)
        self.header.setStyleSheet("QWidget {\n"
"    border-bottom: 3px solid #D8DBD9; \n"
"}\n"
"")
        self.header.setObjectName("header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.headerLabel = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.headerLabel.setFont(font)
        self.headerLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.headerLabel.setStyleSheet("QLabel {\n"
"    color: #67B99A;\n"
"    font-size: 45px;\n"
"}")
        self.headerLabel.setScaledContents(False)
        self.headerLabel.setObjectName("headerLabel")
        self.horizontalLayout_3.addWidget(self.headerLabel)
        self.verticalLayout_3.addWidget(self.header)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.mainContent = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainContent.sizePolicy().hasHeightForWidth())
        self.mainContent.setSizePolicy(sizePolicy)
        self.mainContent.setObjectName("mainContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainContent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainLabel = QtWidgets.QLabel(self.mainContent)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.mainLabel.setFont(font)
        self.mainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainLabel.setObjectName("mainLabel")
        self.verticalLayout_2.addWidget(self.mainLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.pwLabel = QtWidgets.QLabel(self.mainContent)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pwLabel.setFont(font)
        self.pwLabel.setObjectName("pwLabel")
        self.verticalLayout_2.addWidget(self.pwLabel)
        self.widget_2 = QtWidgets.QWidget(self.mainContent)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.passwordFIELD = QtWidgets.QLineEdit(self.widget_2)
        self.passwordFIELD.setMinimumSize(QtCore.QSize(400, 50))
        self.passwordFIELD.setMaximumSize(QtCore.QSize(400, 50))
        self.passwordFIELD.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border-top: 2px solid #67B99A;\n"
"    border-left: 2px solid #67B99A;\n"
"    border-bottom: 2px solid #67B99A;\n"
"    border-right: none;\n"
"    border-top-left-radius: 6px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-top-right-radius: 0;\n"
"    border-bottom-right-radius: 0;\n"
"    background-color: #FFFFFF;\n"
"    selection-background-color: darkgray;\n"
"}\n"
"")
        self.passwordFIELD.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.passwordFIELD.setObjectName("passwordFIELD")
        self.horizontalLayout_2.addWidget(self.passwordFIELD)
        self.pw_visibilityBTN = QtWidgets.QPushButton(self.widget_2)
        self.pw_visibilityBTN.setMinimumSize(QtCore.QSize(35, 50))
        self.pw_visibilityBTN.setMaximumSize(QtCore.QSize(35, 50))
        self.pw_visibilityBTN.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    border-top: 2px solid #67B99A;\n"
"    border-left: none;\n"
"    border-bottom: 2px solid #67B99A;\n"
"    border-right: 2px solid #67B99A;\n"
"    border-top-left-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"")
        self.pw_visibilityBTN.setText("")
        self.pw_visibilityBTN.setObjectName("pw_visibilityBTN")
        self.horizontalLayout_2.addWidget(self.pw_visibilityBTN)
        self.verticalLayout_2.addWidget(self.widget_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.retypeLabel = QtWidgets.QLabel(self.mainContent)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.retypeLabel.setFont(font)
        self.retypeLabel.setObjectName("retypeLabel")
        self.verticalLayout_2.addWidget(self.retypeLabel)
        self.widget_3 = QtWidgets.QWidget(self.mainContent)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.retypeFIELD = QtWidgets.QLineEdit(self.widget_3)
        self.retypeFIELD.setMinimumSize(QtCore.QSize(400, 50))
        self.retypeFIELD.setMaximumSize(QtCore.QSize(400, 50))
        self.retypeFIELD.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border-top: 2px solid #67B99A;\n"
"    border-left: 2px solid #67B99A;\n"
"    border-bottom: 2px solid #67B99A;\n"
"    border-right: none;\n"
"    border-top-left-radius: 6px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-top-right-radius: 0;\n"
"    border-bottom-right-radius: 0;\n"
"    background-color: #FFFFFF;\n"
"    selection-background-color: darkgray;\n"
"}\n"
"")
        self.retypeFIELD.setObjectName("retypeFIELD")
        self.horizontalLayout_6.addWidget(self.retypeFIELD)
        self.rp_visibilityBTN = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rp_visibilityBTN.sizePolicy().hasHeightForWidth())
        self.rp_visibilityBTN.setSizePolicy(sizePolicy)
        self.rp_visibilityBTN.setMinimumSize(QtCore.QSize(35, 50))
        self.rp_visibilityBTN.setMaximumSize(QtCore.QSize(35, 50))
        self.rp_visibilityBTN.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    border-top: 2px solid #67B99A;\n"
"    border-left: none;\n"
"    border-bottom: 2px solid #67B99A;\n"
"    border-right: 2px solid #67B99A;\n"
"    border-top-left-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"")
        self.rp_visibilityBTN.setText("")
        self.rp_visibilityBTN.setObjectName("rp_visibilityBTN")
        self.horizontalLayout_6.addWidget(self.rp_visibilityBTN)
        self.verticalLayout_2.addWidget(self.widget_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.buttonWidget = QtWidgets.QWidget(self.mainContent)
        self.buttonWidget.setObjectName("buttonWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.buttonWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.saveBTN = QtWidgets.QPushButton(self.buttonWidget)
        self.saveBTN.setMinimumSize(QtCore.QSize(200, 50))
        self.saveBTN.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveBTN.setFont(font)
        self.saveBTN.setStyleSheet("QPushButton {\n"
"    background-color: #67B99A;\n"
"    color: white;\n"
"    border: 2px solid #67B99A;\n"
"    padding: 8px 16px;\n"
"    border-radius: 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5CAE8B;\n"
"    border: 2px solid #5CAE8B;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #4D9C7F;\n"
"    border: 2px solid #4D9C7F;\n"
"}")
        self.saveBTN.setObjectName("saveBTN")
        self.horizontalLayout_5.addWidget(self.saveBTN)
        self.cancelBTN = QtWidgets.QPushButton(self.buttonWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBTN.sizePolicy().hasHeightForWidth())
        self.cancelBTN.setSizePolicy(sizePolicy)
        self.cancelBTN.setMinimumSize(QtCore.QSize(200, 50))
        self.cancelBTN.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelBTN.setFont(font)
        self.cancelBTN.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid #67B99A;\n"
"    color: black;\n"
"    padding: 8px 16px;\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #4D926D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;\n"
"    border: 2px solid #265C42;\n"
"}")
        self.cancelBTN.setObjectName("cancelBTN")
        self.horizontalLayout_5.addWidget(self.cancelBTN)
        self.verticalLayout_2.addWidget(self.buttonWidget)
        self.horizontalLayout_4.addWidget(self.mainContent)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_3.addWidget(self.widget)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.headerLabel.setText(_translate("MainWindow", "PASSWORD RECOVERY"))
        self.mainLabel.setText(_translate("MainWindow", "RESET PASSWORD"))
        self.pwLabel.setText(_translate("MainWindow", "Enter new password"))
        self.passwordFIELD.setPlaceholderText(_translate("MainWindow", "New Password"))
        self.retypeLabel.setText(_translate("MainWindow", "Retype New Password"))
        self.retypeFIELD.setPlaceholderText(_translate("MainWindow", "Confirm your Password"))
        self.saveBTN.setText(_translate("MainWindow", "SAVE"))
        self.cancelBTN.setText(_translate("MainWindow", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
