# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screens/ui/help/help_userManual.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.navBar = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navBar.sizePolicy().hasHeightForWidth())
        self.navBar.setSizePolicy(sizePolicy)
        self.navBar.setStyleSheet("QWidget {\n"
"    border-right: 3px solid #D8DBD9;\n"
"}\n"
"")
        self.navBar.setObjectName("navBar")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.navBar)
        self.verticalLayout_7.setSpacing(7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.addUserButton = QtWidgets.QPushButton(self.navBar)
        self.addUserButton.setMinimumSize(QtCore.QSize(100, 100))
        self.addUserButton.setMaximumSize(QtCore.QSize(100, 100))
        self.addUserButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid #67B99A;\n"
"    color: black;\n"
"    padding: 8px 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #4D926D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;\n"
"    border: 2px solid #265C42;\n"
"}\n"
"\n"
"")
        self.addUserButton.setObjectName("addUserButton")
        self.verticalLayout_7.addWidget(self.addUserButton)
        self.editUserButton = QtWidgets.QPushButton(self.navBar)
        self.editUserButton.setMinimumSize(QtCore.QSize(100, 100))
        self.editUserButton.setMaximumSize(QtCore.QSize(100, 100))
        self.editUserButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.editUserButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid #67B99A;\n"
"    color: black;\n"
"    padding: 8px 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #4D926D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;\n"
"    border: 2px solid #265C42;\n"
"}")
        self.editUserButton.setAutoRepeat(False)
        self.editUserButton.setAutoExclusive(False)
        self.editUserButton.setObjectName("editUserButton")
        self.verticalLayout_7.addWidget(self.editUserButton)
        self.pushButton = QtWidgets.QPushButton(self.navBar)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid #67B99A;\n"
"    color: black;\n"
"    padding: 8px 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #4D926D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;\n"
"    border: 2px solid #265C42;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.backButton = QtWidgets.QPushButton(self.navBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        self.backButton.setMinimumSize(QtCore.QSize(100, 100))
        self.backButton.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid #67B99A;\n"
"    color: black;\n"
"    padding: 8px 16px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #4D926D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;\n"
"    border: 2px solid #265C42;\n"
"}")
        self.backButton.setAutoRepeat(False)
        self.backButton.setObjectName("backButton")
        self.verticalLayout_7.addWidget(self.backButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.navBar, 1, 0, 1, 1)
        self.header = QtWidgets.QWidget(self.frame)
        self.header.setStyleSheet("QWidget {\n"
"    border-bottom: 3px solid #D8DBD9; \n"
"}\n"
"")
        self.header.setObjectName("header")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.titleLabel = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.titleLabel.setFont(font)
        self.titleLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titleLabel.setStyleSheet("QLabel {\n"
"    color: #67B99A;\n"
"    font-size: 45px;\n"
"}")
        self.titleLabel.setScaledContents(False)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_13.addWidget(self.titleLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.sysTimeDate = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sysTimeDate.setFont(font)
        self.sysTimeDate.setStyleSheet("QLabel {\n"
"    color: black;\n"
"}")
        self.sysTimeDate.setObjectName("sysTimeDate")
        self.horizontalLayout_13.addWidget(self.sysTimeDate)
        self.gridLayout_2.addWidget(self.header, 0, 0, 1, 2)
        self.mainContent = QtWidgets.QWidget(self.frame)
        self.mainContent.setObjectName("mainContent")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainContent)
        self.horizontalLayout_2.setContentsMargins(25, 25, 25, 25)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pdfViewerPlaceholder = QtWidgets.QWidget(self.mainContent)
        self.pdfViewerPlaceholder.setObjectName("pdfViewerPlaceholder")
        self.horizontalLayout_2.addWidget(self.pdfViewerPlaceholder)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.zoomin = QtWidgets.QPushButton(self.mainContent)
        self.zoomin.setMinimumSize(QtCore.QSize(25, 25))
        self.zoomin.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setBold(True)
        self.zoomin.setFont(font)
        self.zoomin.setStyleSheet("QPushButton {\n"
"    background-color: #67B99A;\n"
"    color: white;\n"
"    border: 2px solid #67B99A;\n"
"    border-radius: 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5CAE8B;\n"
"    border: 2px solid #5CAE8B;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #4D9C7F;\n"
"    border: 2px solid #4D9C7F;\n"
"}")
        self.zoomin.setObjectName("zoomin")
        self.verticalLayout_2.addWidget(self.zoomin)
        self.zoomout = QtWidgets.QPushButton(self.mainContent)
        self.zoomout.setMinimumSize(QtCore.QSize(25, 25))
        self.zoomout.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setBold(True)
        self.zoomout.setFont(font)
        self.zoomout.setStyleSheet("QPushButton {\n"
"    background-color: #67B99A;\n"
"    color: white;\n"
"    border: 2px solid #67B99A;\n"
"    border-radius: 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5CAE8B;\n"
"    border: 2px solid #5CAE8B;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #4D9C7F;\n"
"    border: 2px solid #4D9C7F;\n"
"}")
        self.zoomout.setObjectName("zoomout")
        self.verticalLayout_2.addWidget(self.zoomout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addWidget(self.mainContent, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addUserButton.setText(_translate("MainWindow", "FAQs"))
        self.editUserButton.setText(_translate("MainWindow", "Manual"))
        self.pushButton.setText(_translate("MainWindow", "Support"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.titleLabel.setText(_translate("MainWindow", "HELP"))
        self.sysTimeDate.setText(_translate("MainWindow", "November 28th 2023, 12:07AM"))
        self.zoomin.setText(_translate("MainWindow", "+"))
        self.zoomout.setText(_translate("MainWindow", "-"))
import assets.resourceFile_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
