# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("#widget {\n"
"    background-color: #07BEB8;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #fff;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #808080;\n"
"    border-radius: 5px;\n"
"    background-color: #fff;\n"
"    margin-top: 6px;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    bottom: 5px;\n"
"    padding: 0 5px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 59, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(209, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 64, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.companyName = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.companyName.setFont(font)
        self.companyName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.companyName.setObjectName("companyName")
        self.verticalLayout_4.addWidget(self.companyName)
        self.loginHeader = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.loginHeader.setFont(font)
        self.loginHeader.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loginHeader.setObjectName("loginHeader")
        self.verticalLayout_4.addWidget(self.loginHeader)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userlineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.userlineEdit.setMinimumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        font.setBold(False)
        self.userlineEdit.setFont(font)
        self.userlineEdit.setText("")
        self.userlineEdit.setObjectName("userlineEdit")
        self.verticalLayout.addWidget(self.userlineEdit)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pwdlineEdit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        font.setBold(False)
        self.pwdlineEdit.setFont(font)
        self.pwdlineEdit.setText("")
        self.pwdlineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pwdlineEdit.setObjectName("pwdlineEdit")
        self.verticalLayout_2.addWidget(self.pwdlineEdit)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.login_btn = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("QPushButton {\n"
"    background-color: #036666;\n"
"    color: #fff;\n"
"    border: 5px solid #036666;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked {\n"
"    background-color: #99E2B4;\n"
"    border: 5px solid #99E2B4;\n"
"}")
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout_4.addWidget(self.login_btn)
        self.forgot_btn = QtWidgets.QPushButton(parent=self.widget)
        self.forgot_btn.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.forgot_btn.setFont(font)
        self.forgot_btn.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked {\n"
"    color: #99E2B4;\n"
"}")
        self.forgot_btn.setObjectName("forgot_btn")
        self.verticalLayout_4.addWidget(self.forgot_btn)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 53, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem5, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(209, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 59, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.companyName.setText(_translate("MainWindow", "Moonhey Hotpot"))
        self.loginHeader.setText(_translate("MainWindow", "LOGIN"))
        self.groupBox.setTitle(_translate("MainWindow", "Username"))
        self.userlineEdit.setPlaceholderText(_translate("MainWindow", "Username"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Password"))
        self.pwdlineEdit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.login_btn.setText(_translate("MainWindow", "LOGIN"))
        self.forgot_btn.setText(_translate("MainWindow", "Forgot your password?"))
