# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screens/ui/authentication/emailScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.mainContent = QtWidgets.QVBoxLayout()
        self.mainContent.setObjectName("mainContent")
        self.logoFrame = QtWidgets.QFrame(self.frame)
        self.logoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoFrame.setObjectName("logoFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.logoFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo = QtWidgets.QLabel(self.logoFrame)
        self.logo.setEnabled(True)
        self.logo.setMaximumSize(QtCore.QSize(250, 80))
        self.logo.setStyleSheet("")
        self.logo.setText("")
        self.logo.setTextFormat(QtCore.Qt.AutoText)
        self.logo.setPixmap(QtGui.QPixmap(":/logos/Icons/logo1.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setWordWrap(False)
        self.logo.setObjectName("logo")
        self.horizontalLayout_3.addWidget(self.logo)
        self.mainContent.addWidget(self.logoFrame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainContent.addItem(spacerItem2)
        self.instructionLabel = QtWidgets.QLabel(self.frame)
        self.instructionLabel.setMinimumSize(QtCore.QSize(400, 0))
        self.instructionLabel.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setKerning(False)
        self.instructionLabel.setFont(font)
        self.instructionLabel.setTextFormat(QtCore.Qt.AutoText)
        self.instructionLabel.setScaledContents(False)
        self.instructionLabel.setWordWrap(True)
        self.instructionLabel.setIndent(-1)
        self.instructionLabel.setObjectName("instructionLabel")
        self.mainContent.addWidget(self.instructionLabel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainContent.addItem(spacerItem3)
        self.emailLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.mainContent.addWidget(self.emailLabel)
        self.emailTextBox = QtWidgets.QLineEdit(self.frame)
        self.emailTextBox.setMinimumSize(QtCore.QSize(0, 46))
        self.emailTextBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.emailTextBox.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 2px solid #ADD8E6;\n"
"    border-radius: 6px;\n"
"    background-color: #FFFFFF;\n"
"    selection-background-color: darkgray;\n"
"}")
        self.emailTextBox.setObjectName("emailTextBox")
        self.mainContent.addWidget(self.emailTextBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainContent.addItem(spacerItem4)
        self.continueButton = QtWidgets.QPushButton(self.frame)
        self.continueButton.setMinimumSize(QtCore.QSize(0, 56))
        self.continueButton.setMaximumSize(QtCore.QSize(400, 46))
        self.continueButton.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    border: 1px solid #036666;\n"
"    border-radius: 6px;\n"
"    background-color: #036666;\n"
"    color: white;\n"
"    font-size: 20px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #049393;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #024c4c;\n"
"}")
        self.continueButton.setObjectName("continueButton")
        self.mainContent.addWidget(self.continueButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainContent.addItem(spacerItem5)
        self.backBTN = QtWidgets.QPushButton(self.frame)
        self.backBTN.setMinimumSize(QtCore.QSize(0, 46))
        self.backBTN.setMaximumSize(QtCore.QSize(16777215, 46))
        self.backBTN.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    border: 1px solid #E6E6E6;\n"
"    border-radius: 6px;\n"
"    background-color: #FFFFFF;\n"
"    color: #036666;\n"
"    font-size: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6E6E6;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #CCCCCC;\n"
"}\n"
"")
        self.backBTN.setObjectName("backBTN")
        self.mainContent.addWidget(self.backBTN)
        spacerItem6 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainContent.addItem(spacerItem6)
        self.helpLabel = QtWidgets.QLabel(self.frame)
        self.helpLabel.setMinimumSize(QtCore.QSize(400, 0))
        self.helpLabel.setMaximumSize(QtCore.QSize(400, 16777215))
        self.helpLabel.setSizeIncrement(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.helpLabel.setFont(font)
        self.helpLabel.setTextFormat(QtCore.Qt.AutoText)
        self.helpLabel.setScaledContents(False)
        self.helpLabel.setWordWrap(True)
        self.helpLabel.setObjectName("helpLabel")
        self.mainContent.addWidget(self.helpLabel)
        self.gridLayout_3.addLayout(self.mainContent, 2, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 2, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.instructionLabel.setText(_translate("MainWindow", "Enter the e-mail associated with your account and we’ll send you OTP to reset your password."))
        self.emailLabel.setText(_translate("MainWindow", "E-mail"))
        self.continueButton.setText(_translate("MainWindow", "Continue"))
        self.backBTN.setText(_translate("MainWindow", "Back"))
        self.helpLabel.setText(_translate("MainWindow", "If you don’t have an account, please coordinate with your manager for registering an account through admin."))
import assets.resourceFile_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())